bno055:
  ros__parameters:
    ros_topic_prefix: "bno055/"
    connection_type: "i2c"
    i2c_bus: 1
    i2c_addr: 0x28
    data_query_frequency: 100
    calib_status_frequency: 0.1
    frame_id: "imu_link" # was bno055
    operation_mode: 0x0C
    placement_axis_remap: "P2"
    acc_factor: 100.0
    mag_factor: 16000000.0
    gyr_factor: 900.0
    grav_factor: 100.0
    set_offsets: false
